### PR TITLE
Add SolutionBinary, SolutionName constants for getting solution path.

### PR DESCRIPTION
**Pull request by dariusstrasel**

### CODE REVIEW

**Comment by dariusstrasel** [comment]
@mechamecho Can you checkout develop and see if these new constants correctly evaluate for your computer?

**Comment by mechamecho** [comment]
They do evaluate correctly! Awesome!

**Comment by dariusstrasel** [comment]
Awesome!

**Comment by mechamecho** [comment]
I am still getting the InvalidCastException though

**Comment by dariusstrasel** [comment]
Same. Im looking into it now. Im thinking it has something to do with how we invoke the JObject. Maybe requesting a type and converting it into another unlike type... like JSON array to C# string.

**Comment by dariusstrasel** [comment]
I'm thinking a design flaw of the JSONReader is that it lets the user deserialize the object in an ad hoc manner without being mindful of the full JSON structure... which lets the user request things from JSON that don't exist. Instead, JSONReader should convert directly to C#, and then the user can query the C# objects instead, without affecting the way the JSON gets serialized.

**Comment by dariusstrasel** [comment]
I'm debugging/digging in at the moment.  I dont have a direct-to-code solution in mind yet.

What do you think?

**Comment by dariusstrasel** [comment]
So, whenever converting JSON to C#, you have to explicitly define the types when casting from JSON to C#. You can provide a class or data structure for the  deserializer to map JSON to... 

[Source](https://www.newtonsoft.com/json/help/html/deserializeobject.htm)
```C#
public class Account
{
    public string Email { get; set; }
    public bool Active { get; set; }
    public DateTime CreatedDate { get; set; }
    public IList<string> Roles { get; set; }
}
```
```C#
 string json = @"{
   'Email': 'james@example.com',
   'Active': true,
   'CreatedDate': '2013-01-20T00:00:00Z',
   'Roles': [
     'User',
     'Admin'
   ]
 }";

Account account = JsonConvert.DeserializeObject<Account>(json);

Console.WriteLine(account.Email);
// james@example.com
```
In the case of JSONReader, we are deserializing individual object properties, arrays, etc, in a function by function case. I think as a next step in improving the existing design (ignoring what I said earlier about it being bad) we'd want to create a clearer contract for each of the data-getting functions that get called from JSONReader. For example, which one is getting a List, a object property, etc/

**Comment by mechamecho** [comment]
I see, that makes sense, and seems easier to work with as well. 
I will try that out tomorrow I think. 
Thank you for including the source. I saw it at some point but I didn't pay close attention, so I ended up overlooking this. Good find!

**Comment by mechamecho** [comment]
This basically means that for every collection of testcases, you will need a class that represents the different values. Almost like the POM. Maybe I am way off about that though lol

**Comment by dariusstrasel** [comment]
Yes, it seems like you have to provide classes... Or deserialize it ad hoc! It's much like POM, but I kind of don't like it. You have to write the JSON twice essentially.

I did some digging and there appears to be a way to dynamically query the JSON without specifying a class:
https://www.newtonsoft.com/json/help/html/QueryJsonDynamic.htm

I will look into it more tomorrow or the day after. Feel free to check out the link for more info.

**Pull request merged**
